### ISSUE TITLE
which nerd font is this?

### ISSUE THREAD

**Issue by Only-Moon** [AB10110F/Winfetch-Themes#1]
The nerd font link you have in Readme takes you to the nerd website but on the website, there are a lot of different options available. Do you know which nerd font you used in the preview? btw I like the Japanese version, so I need that font name

**Comment by AB10110F** [comment]
It is Hack nerd font.

**Comment by Only-Moon** [comment]
Which version of Hack Nerd. there are different version for that too.

Sorry for asking too much and causing your inconvenience

________________________________

**Comment by AB10110F** [comment]
Don't worry, it is fine. Do you refer to the different options that come in the compressed file? If so it is Hack Regular Nerd Font Complete Windows Compatible.ttf, if not can you show me the options that appear to you?

**Comment by Only-Moon** [comment]
Yes thanks, that's what I was asking for

________________________________
